### PR TITLE
UpdateEngine and Abstractions v0.3.2

### PR DESCRIPTION
**Pull request by ryanelian**
- `SegaDownloader.MergePatchlist` now has an internal blacklist for certain files that are never to be downloaded. (Instead of merely ignoring stuffs that contains `data/win32/script/`  in the name)

- Added `EnglishPatchVersion`, `EnglishLargePatchVersion`, `StoryPatchVersion` property signatures to the `ITweakerSettings`.

- Implemented those new `ITweakerSettings` methods against existing Tweaker Windows Registry keys in `RegistryTweakerSettings`.

- `UpdateManager.RestoreBackupFiles` now flags those three patch versions as "Not Installed" upon completion.

----

## TODOs:

- Support prepatching. Phase 1: Add an offline patching repository for the downloaded prepatch, that will be used before patch downloads by comparing the repository file listing against the missing files list.

**UNTIL THIS FEATURE IS IMPLEMENTED, PLEASE DO NOT SUPPORT PREPATCHES. 
THE NEXT TIME SEGA DOES PREPATCHES, I WILL EXPERIMENT WITH THE FEATURE!**

- Enable updating the game version `version.ver` in `%USERPROFILE%\Documents\SEGA\PHANTASYSTARONLINE2`.

- Remove `IRenderer.WriteLine`. [Apparently AIDA is displeased with how `UpdateEngine` directly writes into the UI](https://github.com/Arks-Layer/PSO2Tweaker/blob/unstable/PSO2%20Tweaker/frmMain.vb#L2947-L2968). Future version will fine-grain the `IRenderer` with more methods that will be emitted instead by the `UpdateEngine` for improved separation of concerns.

- Remind AIDA that `done.log` should also be deleted [if update resume is cancelled](https://github.com/Arks-Layer/PSO2Tweaker/blob/unstable/PSO2%20Tweaker/frmMain.vb#L446) (if exists).

- Refactor out `done.log` writing mechanism to new class as the basis for GrandLibrary updater module.

### CODE REVIEW

**Comment by TheCrimsonDevil** [comment]
>Remove IRenderer.WriteLine. Apparently AIDA is displeased with how UpdateEngine directly writes into the UI. Future version will fine-grain the IRenderer with more methods that will be emitted instead by the UpdateEngine for improved separation of concerns.

What? I don't have a problem with how this works at all. I prefer the strings the engine uses personally, but if we start talking about hashes, people are going to think we're talking about hashbrowns and potatoes. There's no need to change it IMO, it works perfectly as is.

>Remind AIDA that done.log should also be deleted if update resume is cancelled (if exists).

Fixed, thank ya~

**Comment by TheCrimsonDevil** [comment]
Question:

Can you implement a method that simply checks for missing files and 0KB files (which there shouldn't be because of the legacy thing) and if it finds any, downloads them using the same IRenderers as the normal method?

**Comment by ryanelian** [comment]
> Can you implement a method that simply checks for missing files and 0KB files (there shouldn't be many because of the legacy thing) and if it finds any, downloads them using the same IRenderers as the normal method?

Wat. 

I don't understand this request.

What 0KB files?

Why went a special length for those files instead of just letting the normal update process do the magic?

**Comment by TheCrimsonDevil** [comment]
We have a method "Check for missing/0KB files" for people who mod/mess with files/work on stuff for when they dun goofed, so they don't have to repatch/rehash the entire game for a few files.

**Comment by ryanelian** [comment]
> We have a method "Check for missing/0KB files" for people who mod/mess with files/work on stuff for when they dun goofed, so they don't have to repatch/rehash the entire game for a few files.

My initial reaction to those people would actually be: "You deserve that for not backing up the files. Enjoy rehashing everything".

But sure, I can simply add a parameter to the `Update` method for this case.

> What? I don't have a problem with how this works at all. I prefer the strings the engine uses personally, but if we start talking about hashes, people are going to think we're talking about hashbrowns and potatoes. There's no need to change it IMO, it works perfectly as is.

Hmmm... Okay, I won't change it for now.

**Comment by ryanelian** [comment]
> But sure, I can simply add a parameter to the `Update` method for this case.

Just a quick warning tho, even though I am about to implement this.

You should know that if someone opted to do this before an update, instead of doing the normal shit, it CAN and WILL break their client. 

Let's say a human decided to mess with file A. File A is now gone.

Suddenly there's a game update and that guy isn't aware of that. The guy decided to do quickly check on missing files instead of running the Update normally.

Yay File A is restored.

# HOWEVER

File B actually changed from the past client in this update!

But because File B is actually not missing nor damaged (0KB), it will not get downloaded by the updater!

Are you sure you want to support this?

**Comment by TheCrimsonDevil** [comment]
Hahaha, I get it, I get it! We shouldn't do it this way xD So we won't :+1:

**Pull request merged**
