### PR TITLE
Version 0.2.0 UpdateEngine + Abstractions

### PR DESCRIPTION
**Pull request by ryanelian**
First, I apologize for the rapid shipment but better now than later after the new Tweaker has been deployed. (While now it's still in the `unstable` branch)

## UpdateEngine + Abstractions v0.2.0 Change Log 

- `IRenderer.OnDownloadStart` method now sends the `WebClient` as parameter. This object can be used to terminate a stuck download using the UI control.

- Legacy files cleanup is integrated into the `UpdateManager.Update` pipeline. **YOLO**.
(For 3 days it didn't cause any major damage to my client. So yeah, let's give this a try to the general public.)

- Set a more liberal update interval for hash progress and download progress to 2 seconds down from 5 seconds.

- Fixed a bug with writing to `done.log` that broke resume functionality! :cake: 

- Removed specially compiled references to .NET Framework 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2 to save bytes. The version 4.5 is apparently compatible with them anyways.

## UpdateEngine v.0.2.2 Change Log

- `UpdateManager.RehashWholeClient` now offloads hashing job to background thread and keeps the progress monitoring in UI thread instead of the other way around!

- Added a parameter to `UpdateManager.Update` signature for whether it should run legacy files clean-up or not.

- Deleted all other packages that weren't the latest so AIDA is forced to use the latest lololol.

### CODE REVIEW

**Comment by ryanelian** [comment]
Working as intended. Isn't how it can skip half of the workload almost immediately is pretty awesome?

File size is sorted from small to large then hard disk buffer is increased from 4KB up to 4MB max in a multiply of 2, in a hill-climbing algorithm fashion.
This allows it to instantly load most files within 1 buffer until it meet files that are more than 4MB in size (last 1800 files) that require efforts to read.

This ordering also allows the program to defeat the notorious Branch Predictor Failure when working with many data sets with variable input. (In this case, the hard disk buffer. It's much more efficient for the disk to climb from 4KB --> 8KB --> 16KB --> etc. than randomly up-and-down-ing the buffer size like 8KB->1MB->4KB->256KB)
https://en.wikipedia.org/wiki/Branch_predictor

The last file is 500MB so yeah it takes awhile there. :smile:

**Comment by TheCrimsonDevil** [comment]
Oooooooh, I see! Just wanted to make sure I wasn't doing anything wrong :+1:  It's a HUGE improvement, and I love it <3 Thanks for all your hard work! \ o / Time for me to get back to coding now :D

**Comment by TheCrimsonDevil** [comment]
Question: Where/how are the previous client hashes saved?

**Comment by ryanelian** [comment]
Previous client hashes: `client.json`

Ongoing update patchlist: `patchlist.json`

Ongoing update detected missing files: `missing.json`

Ongoing update downloaded files: `done.log`
(There is a minor edge case bug in `done.log` handling that I haven't shipped btw. It will occur if somewhat the user terminated the update process way before any files get downloaded, which is unlikely, but possible.)

Why thank you :D

**Pull request merged**
