### PR TITLE
UpdateEngine v0.2.3

### PR DESCRIPTION
**Pull request by ryanelian**
Sorry for interrupting your zen coding session, but here's some bug fixes and minor improvements to the UpdateEngine.

## UpdateEngine v0.2.3 Change Log

-  Added error trap against done.log not found. Prevent edge cases like when a user terminates the update process before ANYTHING has finished downloading. Unlikely but possible. Better be safe than sorry.

- Added diagnostic logging for each patch file download. 

- Added diagnostic logging for each file backup restore. 

- Reordered download progress UI update code lines for improved refresh cycle.

-  Changed behavior of patch resume: now will not update the missing file JSON after reading it and subtracting from the done.log, since done.log is not altered anyway after resuming patch. (Prevents unwanted bug due to file IO)

- Improved performance of comparing missing files to done.log using HashSet comparison, from O(N^2) to O(N)!

- Improved performance of legacy file cleansing using clever query parallelization.

### CODE REVIEW

**Comment by ryanelian** [comment]
Next performance improvement candidate:

Apparently the standard pipeline of the non-resume update is Backup Restore --> Patchlist Download --> Clean Legacy Files --> Get Client Hash --> Missing Files Discovery --> Download Updates --> Update Client Hash File --> Housekeeping

Backup Restore and Patchlist Download apparently don't rely on each other's completion and can be completed in tandem:

- If there are MANY files to restore (English Patch + Large English Patch + Story Patch), update will take more than a few seconds to complete. That few seconds can be utilized for asynchronous patchlist download operation.

- Kick off patchlist download in advance then perform backup restore synchronously. The next step (Legacy Files Cleansing) requires both step to be completed so patchlist download can be awaited after the backup completed.

----

Pre-patch implementation can be performed cleanly by using that standard pipeline, integrated into the Download Updates process.

Pre-patch downloaded can be transformed into offline repository with a separate patch-hash dictionary JSON that can be read after the missing files discovery. If a missing file exists in the pre-patch directory, will move / copy the file instead of downloading.

This way, there are no needs to implement a manual patchlist maintenance and instead can follow the standard patchlist issuance.

**Comment by TheCrimsonDevil** [comment]
Question! The update engine always fails to download these two files (which I usually just ignore in the "old" update code.):

http://download.pso2.jp/patch_prod/patches_old/data/win32/script/user_intel.pso2.pat
http://download.pso2.jp/patch_prod/patches/data/win32/script/user_default.pso2.pat

Also, is there any way to get how many files total need to be downloaded for a "Downloaded X out of Y files". I have X working, just need a way to get Y :3

Awesome work. This is looking soooo good :D

**Comment by TheCrimsonDevil** [comment]
Another question: Does this/will this support the pso2.exe and base directory (as opposed to win32) files?

**Comment by ryanelian** [comment]
> Question! The update engine always fails to download these two files (which I usually just ignore in the "old" update code.):

>http://download.pso2.jp/patch_prod/patches_old/data/win32/script/user_intel.pso2.pat
>http://download.pso2.jp/patch_prod/patches/data/win32/script/user_default.pso2.pat

I... uh... what? That's news for me. I can ignore them If they never succeed, I guess.

> Also, is there any way to get how many files total need to be downloaded for a "Downloaded X out of Y files". I have X working, just need a way to get Y :3

At the moment no, but I emit another IRenderer method that does that for you.

Or alternatively you can capture how many downloads there are by just incrementing an `integer` everytime IRenderer.OnDownloadStart happens.

> Another question: Does this/will this support the pso2.exe and base directory (as opposed to win32) files?

I don't really understand what you mean by support.

IIRC if the stuffs in the base directory gets updated, for example `pso2.exe`, as indicated in the downloaded patchlists, it will automatically download them.

**Comment by TheCrimsonDevil** [comment]
>I... uh... what? That's news for me. I can ignore them If they never succeed, I guess.

It's not that I don't trust you, but they were successful for me in the first attempt after this post:

That's really odd, they've failed for me every time:
scriptdl

>Anyways, since they're not needed by the client, I will ignore anything in `data/win32/script/` folder for convenience, in future version.

kk, works for me \ o /

>At the moment no, but I emit another `IRenderer` method that does that for you, if I must.

If you could, yes. I'm going to be adding in more download bars (like in that screenshot), but I'll need to update the status text with the total downloads. 

Speaking of downloads, is there a maximum amount of simultaneous downloads?

>IIRC if the stuffs in the base directory gets updated, for example `pso2.exe`, as indicated in the downloaded patchlists, it will automatically download them.

Ah, I see they do indeed. Good stuff, never mind then!

**Comment by ryanelian** [comment]
> If you could, yes. I'm going to be adding in more download bars (like in that screenshot), but I'll need to update the status text with the total downloads. 

Roger that. :crossed_flags: 

> Speaking of downloads, is there a maximum amount of simultaneous downloads?

There are not but `.NET Framework` will manage how many downloads in parallel that happens.

(Let's say all 4000 files download `Task` are started off, `.NET Framework` will attempts to, let's say, do 4 at a times. If 4 is too low because your bandwidth is high, it will up the number to, let's say, 5 or 6. In inverse, it may reduce the amount parallelized if it feels the need to do so)

**Pull request merged**
