### PR TITLE
Appveyor and Costura.Fody support, also moved Exception reading code

### PR DESCRIPTION
**Pull request by alama**
now with a Appveyor, you can make sure that all new Pull Requests do compile (and run any tests, if we had any)

### CODE REVIEW

**Comment by alama** [comment]
Ok, Now ot only does this let the buildbot build Terminal and PSO2 Tweaker, it also use Costura.Fody to place the DLLs inside said  EXEs

https://ci.appveyor.com/project/STJr/pso2tweaker/build/1.0.46/job/tsuyi3qa9rsxjdkg#L50

**Comment by alama** [comment]
Now this PR have same commits for moving the Exception reading code to a pair of sub and function

**Comment by ryanelian** [comment]
We need AppVeyor badge in project main readme.

http://www.appveyor.com/docs/status-badges

So I can grab nightly build for giggles. :+1:

**Comment by alama** [comment]
so

    Build status

Build status

**Comment by ryanelian** [comment]
Almost correct but clicking the badge should link to latest build page.

Something like this README: https://github.com/aspnet/EntityFramework/

**Comment by alama** [comment]
so

    [Build status](https://ci.appveyor.com/project/TheCrimsonDevil/pso2tweaker/branch/master)]

[Build status](https://ci.appveyor.com/project/TheCrimsonDevil/pso2tweaker/branch/master)]

**Comment by ryanelian** [comment]
Badass :+1:

**Pull request merged**
