### PR TITLE
Abstractions v0.4.6

### PR DESCRIPTION
**Pull request by ryanelian**
# Abstractions v0.4.6

- Nice catch, Alama! #45 Now `RegistryTweakerSettings` checks whether PSO2 user folder exists before attempting to write `version.ver` file (it will be created if doesn't exist during value set) and checks whether the file actually exists before trying to read from it. (`GameVersion` property string now returns NULL if file not found!)

- Fixed words in `ConsoleTrigger`.

# UpdateEngine v0.4.8

- `CleanLegacyFiles`, `RestoreBackupFiles`, `EnumerateGameFiles`, `Housekeeping` are now performed in the background and then awaited. **These are done to slightly improve UI responsiveness when update is kickstarted by not blocking the UI thread with too many Disk I/O operation.** :tada: 

- Due to above change, `ITrigger.OnCensorRemoval` can no longer be called, is deprecated, and will be no longer called. (Censor removal message will be appended to log file instead)

### CODE REVIEW

**Comment by TheCrimsonDevil** [comment]
So I decided to stop slamming my head into the wall and get back into this - However I'm running into this issue:

Things broken

It's broken in my project and in your included source code.

**Comment by ryanelian** [comment]
Eeeeeh what is that error O_O

**Comment by ryanelian** [comment]
```
D:\VS\PSO2Tweaker>git reset --hard
HEAD is now at a7e7649 Merge pull request #47 from ryanelian/master
```

tweaker

It works just fine here. Maybe try restarting your VS or do a `git reset --hard` / `git clean -fdx` then attempt to rebuild the project?

**Comment by TheCrimsonDevil** [comment]
Did a git reset --hard and git clean -fdx. Restored everything. Opened project, updated to the latest version of your stuff (which will NOT pass since you changed the names, so I have no idea why the AppVeyor claims to pass, that's impossible), and the moment I update, I have the same issue.

**Pull request merged**
