### PR TITLE
UpdateEngine & Abstractions v0.3.0

### PR DESCRIPTION
**Pull request by ryanelian**
## UpdateEngine & Abstractions v0.3.0 Change Log

-  Made patchlist download asynchronously along with backup restore, then awaited before legacy file cleansing. :zap: 

- Reordered `Output.OnDownloadStart` method call after `WebClient` download async task, to prevent edge cases where user near-instantly cancels the download before it even started!

-  Ignoring `data/win32/script/` folder files in patchlist because they are not needed by the game client and can fail to download for some people. (Weird)

-  As requested, added `IRenderer.OnPatchingStart` that sends an `integer` of how many patch downloads are to be done and will be called right after all downloads are kicked off asynchronously. :gift: 

# Breaking Changes :bomb: 

- Removed `IRenderer.OnDownloadProgress` to relieve `SegaDownloader` of the duty on managing the progress update of the `WebClient`. 

Hint: attach a progress delegate to the `WebClient` in `OnDownloadStart` instead, see `Terminal.ConsoleRenderer` project for example. 

This change is done so AIDA can independently adjust the granularity of the update progress bar refresh instead of being restrained by the engine.

## UpdateEngine v0.3.1

- Internalized most `UpdateEngine` classes.

- Released `UpdateEngine.Housekeeping` API for cleaning up files if patching is aborted.

- Fixed a nasty edge case bug if a user game client is located in a folder that contains the word `backup` and `\data\win32\` in its full path.

- Log all files that are to be hashed.

- Improved some method's XML documentations.

### CODE REVIEW

**Comment by ryanelian** [comment]
More edge cases:

- If the game folder is located in a folder with the full path containing the word `backup` or `\data\win32\`, all hell will break loose. (God forbid someone put the game in something like `C:\backup\data\win32\pso2_bin\...`)

**Comment by TheCrimsonDevil** [comment]
>Removed IRenderer.OnDownloadProgress to relieve SegaDownloader of the duty on managing the progress update of the WebClient.
>Hint: attach a progress delegate to the WebClient in OnDownloadStart instead, see Terminal.ConsoleRenderer project for example.
>This change is done so AIDA can independently adjust the granularity of the update progress bar refresh instead of being restrained by the engine

Could this be reverted? >_< This whole "delegate" process is literally making my head explode. I don't get it at all...

**Comment by ryanelian** [comment]
> Could this be reverted? >_< This whole "delegate" process is literally making my head explode. I don't get it at all...

Isn't that thing is similar to how the usual event handler works?
https://msdn.microsoft.com/en-us/library/ms172877.aspx

Time for programming level up! :D
https://msdn.microsoft.com/en-us/library/bb531253.aspx

You already have been using that, but just in different form. What you probably need to do is something like this:

```vb
AddHandler webClient.DownloadProgressChanged, Sub (o, e) 
                                                  'do something here
                                              End Sub
```

**Comment by TheCrimsonDevil** [comment]
Oh, I just now saw your edit XD I leveled up! (And got it all to work \ o /)

**Comment by TheCrimsonDevil** [comment]
@ryanelian  Is there a better way to send you a message?

These files weren't working either:
>Download aborted for http://download.pso2.jp/patch_prod/patches/PSO2JP.ini! [WARNING!]
>Download aborted for http://download.pso2.jp/patch_prod/patches/gameversion.ver! [WARNING!]
>Download aborted for http://download.pso2.jp/patch_prod/patches/GameGuard.des! [WARNING!]
>Failed to download 3 files!

Can you skip those as well? (They're downloaded on PSO2.exe execution, dunno why they even have them in there).

**Comment by ryanelian** [comment]
> Is there a better way to send you a message?

There are better ways to send me messages but I'm not sure which actually allows me to write a code directly for reply. (GitHub markdown is awesome yo.)

> They're downloaded on PSO2.exe execution

Oh? TIL.

Well sure, I can add them to be skipped if you're really sure that they pose no problems when not downloaded.

 > Also, is there a method to cancel the update?

Yes, you close the launcher. :smile_cat: 

On a serious note, I haven't actually think about how to do this. I think it may involve some sort of `Thread.Abort` magic, but I'm not sure.

**Comment by belldandu** [comment]
Haha. 2 possible ways of contact.

Discord:
you will have to learn the discord markdown for inserting code. Your also
limited to 2000 chars.

Slack:
uses the github markdown if im not mistaken. No idea if it has any
limitations.

Also great progress and amazing job

**Comment by TheCrimsonDevil** [comment]
>Well sure, I can add them to be skipped if you're really sure that they pose no problems when not downloaded.

Excellent! Please make sure the following files are skipped:

- PSO2JP.ini
- GameGuard.des
- gameversion.ver
- user_default.pso2
- user_intel.pso2
- edition.txt

Once these files get ignored, I think it's pretty much ready for public testing \ o /

**Comment by ryanelian** [comment]
> user_default.pso2
> user_intel.pso2

These were in the scripts folder and excluded already, am I right?

> gameversion.ver
> edition.txt

Are you sure? These looks important to the client, but I might be wrong. 

I've sworn that I've seen "4.0302.1" at the bottom right of the game logo screen when launching it.

**Comment by belldandu** [comment]
Btw @TheCrimsonDevil can i get a screenshot of the new look. My laptop
charger and harddrives both finally broke and i had no money to replace
them so i wont really be able to see it otherwise for a long time cause im
stillnlooking for a job and waiting to be told that im good to ship out by
the navy.

**Comment by belldandu** [comment]
Ahaha add me on discord Belldandu#6148 @TheCrimsonDevil also that avatar is
a custom made render from the custom char i got from mugi that he made for
me ;p. Its also my custom char in fragment ;p.

**Comment by TheCrimsonDevil** [comment]
>These were in the scripts folder and excluded already, am I right?

Correct, just wanted to include them for consistency.

>Are you sure? These looks important to the client, but I might be wrong.

You'd think so, but no. I always delete them whenever I update, and in the past 10 months or so, nothing has ever gone wrong without them. The game and updater and everything else uses the version.ver in My Documents, so (again) I have no idea why it's even in there still. I can only imagine it's easier to leave it in than remove it.

>Btw @TheCrimsonDevil can i get a screenshot of the new look. My laptop
charger and harddrives both finally broke and i had no money to replace
them so i wont really be able to see it otherwise for a long time cause im
stillnlooking for a job and waiting to be told that im good to ship out by
the navy.

The new look? The downloading form? Sure.

http://aida.moe/puush/7uRf.png

**Comment by ryanelian** [comment]
Just curious about the GameGuard. Do the `PSO2.exe` manages their versions automatically without us needing to do so, upon launching?

> http://aida.moe/puush/7uRf.png

That looks great. At first I thought the progress bars are going to be dynamic instead of fixed to 6. But if that actually works, then kudos. :+1:

**Comment by belldandu** [comment]
Omg thats sexy <3 can't wait till i start gettingmpaid so i can go get new
shit :D. Currently im doing everything from phone and tablet and i'm mostly
locked out of github and bitbucket (login from the sites i mean cause authy
doesnt sync backups between devices ....)  I can still ssh and stuff but
its a pain.

**Comment by TheCrimsonDevil** [comment]
>Just curious about the GameGuard. Do the PSO2.exe manages their versions automatically without us needing to do so, upon launching?

Yep!

>That looks great. At first I thought the progress bars are going to be dynamic instead of fixed to 6. But if that actually works, then kudos. :+1:

It works wonderfully \ o /

**Pull request merged**
