### PR TITLE
Unstable

### PR DESCRIPTION
**Pull request by TheCrimsonDevil**

### CODE REVIEW

**Comment by ryanelian** [comment]
Nice :+1:

**Comment by TheCrimsonDevil** [comment]
- NEW UPDATE METHOD: QUANTUM SYSTEM
- Combines both of the older update methods into a super-efficient system
- Checking all the files (ala old method) is super fast now
- Checking for only the updated files (ala new method) has been completely rewritten and finishes in *seconds*
- Downloading is now done in parallel, with many files being downloaded at once, which improves patching time considerably.
- The number of files downloaded is done via .NET, which leverages it based on your bandwidth and other variables. This will be configurable in the future.
- Legacy File cleanup is now coded in. This will automatically remove all the junk data files that are no longer used by the game/in the patchlist (I'm looking at you, PSO2 Alpha files!) It currents gives you about 1GB back in free space.
- Removed the "Restore/Remove Censor" options. This is now done automatically on every update.
- New GUI for the downloading process
- New file that logs the patching/downloading process - patchlog.txt
- Lots of bugfixes and optmizations
- Fixed an issue where the Tweaker would sometimes (all the time for some people) crash upon loading GN Field
- All patches now store backups in the backup folder under win32
- The new method does NOT support pre-patching yet, will be worked on during next pre-patch.
- Some UI changes to show the new patching method

**Comment by ryanelian** [comment]
Congratulations on release! :congratulations: :confetti_ball: :tada: :balloon: 

I hope this doesn't break everyone's computer LOL. :clap:

**Comment by ryanelian** [comment]
The UI is not responding when "Beginning QUANTUM SYSTEM update check..."

Is this expected?

**Comment by ryanelian** [comment]
Another issue, when I right click the progress bar during hashing, it says:

- Restart download

- Cancel process

While I don't know if you're able to actually cancel the process (I'd be impressed if you do), I'm pretty sure that `Restart download` is supposed to be there.

**Comment by TheCrimsonDevil** [comment]
@ryanelian People are having crashing issues cleaning up legacy files larger than a certain amount (338MB passed fine, 1.2GB did not)

**Comment by TheCrimsonDevil** [comment]
Some people are crashing after deleting 57 files, some people after 2 - 4

**Comment by ryanelian** [comment]
> People are having crashing issues cleaning up legacy files larger than a certain amount (338MB passed fine, 1.2GB did not)
> Some people are crashing after deleting 57 files, some people after 2 - 4

Geh. Any stack trace I can use to fix this?

**Comment by acffordyce973** [comment]
Tweaker log: http://pastebin.com/n4L4ApXr
Patch log: http://pastebin.com/EWrms3Fy

**Comment by ryanelian** [comment]
> 8/6/2016 4:04:55 PM: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: mscorlib

That's really not helpful :cry: 

I'm impressed tho, 5GB legacy files.

**Comment by TheCrimsonDevil** [comment]
I changed all ex.messages to output the stack trace too. Maybe it's an internal issue and the string is just being passed from your DLL? (git blame am i rite)

**Comment by ryanelian** [comment]
Copying 2000 files into a junk folder will take me 30 minutes, so bear with me for fixing this.

Current course of plan:

- Test if deleting 2000 files crashes the console application in my computer.

- Test if deleting 2000 files crashes the Tweaker in my computer.

- If it crashes at all, attempt to find out why and how it crashed.

**Comment by ryanelian** [comment]
Fortunately destroying 2000 files don't crash the console (and it happened near-instantly), so it cannot be because if the engine failure.

screenshot 2016-08-06 22 43 55

I will now test 2000 files cleanup in the actual Tweaker application.

**Comment by ryanelian** [comment]
Yep confirmed positive bug during deletion of 2000+ legacy files in Tweaker.

capture

**Comment by ryanelian** [comment]
AIDA, tell me what happens to the message: "Fileblablabla deleted." during legacy file cleanup?

**Comment by ryanelian** [comment]
Cheat sheet for above problem:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArksLayer.Tweaker.Terminal
{
    public static class UpdateEngineLogger
    {
        // Thread-safe lock for the file being written
        public static object FileLock = new object();

        public static void AppendLine(string message)
        {
            // We don't need this task to return to original thread, fire and forget
            Task.Run(() =>
            {
                lock(FileLock)
                {
                    // Append message to log here
                }
            }).ConfigureAwait(false);
        }
    }
}
```

**Comment by TheCrimsonDevil** [comment]
Yeah, I realized it was probably this on my way to work. I'll fix it when I get home, good stuff!

**Pull request merged**
